### ISSUE TITLE
UI framework

### ISSUE THREAD

**Issue by cod-cax** [codcax/codlab#4]
### Description

Please check out the optimum CSS framework for the project. Currently, we have two candidates for review which are `tailwindcss` and `mui` .

We have previously utilized `tailwindcss` as it is more of utility type focused rather than full fledge `mui`.  The focus in current project is we should be looking for more of robust and ease to use library without complex / dead codes.

Test with both candidates and provide feedback, asap.

**Comment by Tenesh** [comment]
@cod-cax , based on testing both frameworks, I have also tested `semantic ui` for React compatibility which is similar to `bootstrap`. But, I think we shall resort to `tailwindcss`. 

Develop branch is updated with `tailwindcss` package and had set up required config for it. 
Commit ID: 8c7713e61e139ccd91e5a897550ca18517ec0572
