### ISSUE TITLE
Course feature

### ISSUE THREAD

**Issue by Tenesh** [codcax/codlab#9]
### Description

Course feature is the content and purpose of the App. The App should be able to have multiple Courses depending on content management for instance JS, TS, Python which can be specific to language or more of field scope namely Web Dev, Database, Data Structures and etc.

#### Course should have these attributes:
| Attribute | Description | Required | Example |
|-------|----------|:---:|------|
| Name| Name of the course. | Yes | Introduction to React |
| Scope | Subject matter that is relevant to the course.  | Yes | Programming Language, System Design, Data Structure |
| Level | The difficulty level of the course. | Yes | Enums : `Beginner, Intermediate, Advanced` |
| Chapter | Every Course should have at least 1 Chapter to begin with (Grouping purpose only, no content). | Yes | Overview, Chapter 1 |
| Lesson | Every Chapter should have at least 1 Lesson to begin with. | Yes | Lesson 1, Lesson 2|
| Exercise | Testing material for which can be implemented for each Chapter or as problem for Course. | No | Exercise 1, Exercise 2 |

**Comment by Tenesh** [comment]
@cod-cax , in the case of `Chapter` are looking to have a separate page for each `Chapter` like an overview of the page or it is just for segregation purpose of lessons and grouping?

Currently, for each `Course` : `domain/course/` will display an overview of the course in the `Content` component. Shall this be applicable for `Chapter` too?

**Comment by Tenesh** [comment]
@cod-cax , this is possible. Then, I will make the `Content` component as dynamic prop and keep the `SideBar` and `Hero` components consistent around entire `Course` and it's child routes.

**Comment by cod-cax** [comment]
@Tenesh quick update on `Chapter` component will not have a separate page  and it is intended to be used as segregation only. Currently, we will stick with this path forward. Thus, the route and outlet shall be per:

Course : domain/course-1/
Chapter : No URL path
Lesson : domain/course-1/lesson-1/
Test : domain/course-1/test-1/
